version: "3"

services:
  # Webサーバ
  webserver:
    build: ./docker/nginx
    image: sinatra_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    depends_on:
      - app

  # Sinatraアプリケーション
  app:
    build: ./docker/app
    image: sinatra_app
    working_dir: /app
    volumes:
      - .:/app
    expose:
      - "9292"
    env_file:
      - ./docker/app/envfile
    command: >
      bash -c "bundle install &&
      bundle exec rackup config.ru -o 0.0.0.0"
